### ISSUE TITLE
Some training events are not imported from Breathe to Productive

### ISSUE THREAD

**Issue by erbridge** [dxw/scheduling-event-sync#51]
We've had reports that some training put into Breathe aren't being imported. I don't currently have any theories why, but here is are two examples that exhibit this incorrect behaviour:
<img width="806" alt="Screenshot 2022-06-08 at 11 20 04" src="https://user-images.githubusercontent.com/1027364/172580933-dc04693e-1808-4115-acde-bd8b9e7d36e8.png">
<img width="839" alt="Screenshot 2022-06-08 at 11 20 39" src="https://user-images.githubusercontent.com/1027364/172581061-104e0194-7051-4d80-902b-5a26f51b63ee.png">

**Comment by jdudley1123** [comment]
Closing this issue as I'm not aware of any current problems related to this and we've made quite a few changes since this was raised.
