### ISSUE TITLE
Some leave isn't being imported from Breathe to Productive

### ISSUE THREAD

**Issue by erbridge** [dxw/scheduling-event-sync#52]
At least one leave event wasn't imported from Breathe:
<img width="810" alt="Screenshot 2022-06-08 at 11 21 59" src="https://user-images.githubusercontent.com/1027364/172581388-9d680531-3d2c-4b85-941c-65d874d271fd.png">
This person has had other leave successfully imported before and after this event.

Is it possible that it's something to do with that day being a bank holiday that was moved due to the jubilee?

**Comment by CristinaRO** [comment]
Results from running the task in https://github.com/dxw/scheduling-event-sync/pull/54 are inconclusive, as they show that the date in question *would* be created in Productive.

**Comment by jdudley1123** [comment]
Closing this issue as I'm not aware of any current problems related to this and we've made quite a few changes since this was raised.
